src/main/java/itwill/helljava/dao/AccountDAO.java
src/main/java/itwill/helljava/dao/AccountDAOImpl.java
src/main/java/itwill/helljava/dao/AwardDAO.java
src/main/java/itwill/helljava/dao/AwardDAOImpl.java
src/main/java/itwill/helljava/dao/MemberDAO.java
src/main/java/itwill/helljava/dao/MemberDAOImpl.java
src/main/java/itwill/helljava/dao/NoticeServiceDAO.java
src/main/java/itwill/helljava/dao/NoticeServiceDAOImpl.java
src/main/java/itwill/helljava/dao/PayDAO.java
src/main/java/itwill/helljava/dao/PayDAOImpl.java
src/main/java/itwill/helljava/dao/PostingDAO.java
src/main/java/itwill/helljava/dao/PostingDAOImpl.java
src/main/java/itwill/helljava/dao/PtOnceDAO.java
src/main/java/itwill/helljava/dao/PtOnceDAOImpl.java
src/main/java/itwill/helljava/dao/PtPricingDAO.java
src/main/java/itwill/helljava/dao/PtPricingDAOImpl.java
src/main/java/itwill/helljava/dao/PtServiceDAO.java
src/main/java/itwill/helljava/dao/PtServiceDAOImpl.java
src/main/java/itwill/helljava/dao/ScheduleDAO.java
src/main/java/itwill/helljava/dao/ScheduleDAOImpl.java
src/main/java/itwill/helljava/dao/TrainerDAO.java
src/main/java/itwill/helljava/dao/TrainerDAOImpl.java

DAO 생성 (틀만 잡음)

---

src/main/java/itwill/helljava/service/AccountServiceImpl.java
src/main/java/itwill/helljava/service/AccountSevice.java
src/main/java/itwill/helljava/service/AwardService.java
src/main/java/itwill/helljava/service/AwardServiceImpl.java
src/main/java/itwill/helljava/service/MemberService.java
src/main/java/itwill/helljava/service/MemberServiceImpl.java
src/main/java/itwill/helljava/service/NoticeServiceService.java
src/main/java/itwill/helljava/service/NoticeServiceServiceImpl.java
src/main/java/itwill/helljava/service/PayService.java
src/main/java/itwill/helljava/service/PayServiceImpl.java
src/main/java/itwill/helljava/service/PostingService.java
src/main/java/itwill/helljava/service/PostingServiceImpl.java
src/main/java/itwill/helljava/service/PtOnceService.java
src/main/java/itwill/helljava/service/PtOnceServiceImpl.java
src/main/java/itwill/helljava/service/PtPricingService.java
src/main/java/itwill/helljava/service/PtPricingServiceImpl.java
src/main/java/itwill/helljava/service/PtServiceService.java
src/main/java/itwill/helljava/service/PtServiceServiceImpl.java
src/main/java/itwill/helljava/service/ScheduleService.java
src/main/java/itwill/helljava/service/ScheduleServiceImpl.java
src/main/java/itwill/helljava/service/TrainerService.java
src/main/java/itwill/helljava/service/TrainerServiceImpl.java

Service 생성 [틀만 잡음]

---

src/main/java/itwill/helljava/util/Pager.java

Util 패키지 생성

---

src/main/java/itwill/helljava/mapper/AccountMapper.java
src/main/java/itwill/helljava/mapper/AwardMapper.java
src/main/java/itwill/helljava/mapper/MemberMapper.java
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.java
src/main/java/itwill/helljava/mapper/PayMapper.java
src/main/java/itwill/helljava/mapper/PostingMapper.java
src/main/java/itwill/helljava/mapper/PtOnceMapper.java
src/main/java/itwill/helljava/mapper/PtPricingMapper.java
src/main/java/itwill/helljava/mapper/PtServiceMapper.java
src/main/java/itwill/helljava/mapper/ScheduleMapper.java
src/main/java/itwill/helljava/mapper/TrainerMapper.java

Mapper 생성 (인터페이스만!)

---

src/main/java/itwill/helljava/dto/Pt_once.java
src/main/java/itwill/helljava/dto/Pt_pricing.java
src/main/java/itwill/helljava/dto/Pt_service.java

필요없는 dto 클래스 지움

---

src/main/java/itwill/helljava/dto/PtService.java

필드 철자 Sortation -> sortation 소문자 변경

필드 철자 Sortation -> sortation 소문자 변경

---

src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml

servlet-context 일부 추가

---

src/main/java/itwill/helljava/service/AccountSevice.java
src/main/java/itwill/helljava/service/AwardService.java
src/main/java/itwill/helljava/service/MemberService.java
src/main/java/itwill/helljava/service/NoticeServiceService.java
src/main/java/itwill/helljava/service/PayService.java
src/main/java/itwill/helljava/service/PostingService.java

service 추상 메서드 선언

---

src/main/java/itwill/helljava/service/PtOnceService.java
src/main/java/itwill/helljava/service/PtPricingService.java
src/main/java/itwill/helljava/service/PtServiceService.java
src/main/java/itwill/helljava/service/ScheduleService.java
src/main/java/itwill/helljava/service/TrainerService.java

service commit

---

src/main/java/itwill/helljava/dao/PtOnceDAO.java
src/main/java/itwill/helljava/dao/PtPricingDAO.java
src/main/java/itwill/helljava/dao/PtServiceDAO.java
src/main/java/itwill/helljava/dao/ScheduleDAO.java
src/main/java/itwill/helljava/dao/TrainerDAO.java

dao commit

---

src/main/java/itwill/helljava/dao/AccountDAO.java
src/main/java/itwill/helljava/dao/AwardDAO.java
src/main/java/itwill/helljava/dao/MemberDAO.java
src/main/java/itwill/helljava/dao/NoticeServiceDAO.java
src/main/java/itwill/helljava/dao/PayDAO.java
src/main/java/itwill/helljava/dao/PostingDAO.java

DAO 추상메서드 선언

---

src/main/java/itwill/helljava/mapper/AccountMapper.java
src/main/java/itwill/helljava/mapper/AwardMapper.java
src/main/java/itwill/helljava/mapper/MemberMapper.java
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.java
src/main/java/itwill/helljava/mapper/PayMapper.java
src/main/java/itwill/helljava/mapper/PostingMapper.java

Mapper 추상 메서드 선언

---

src/main/java/itwill/helljava/service/AccountServiceImpl.java
src/main/java/itwill/helljava/service/AwardServiceImpl.java
src/main/java/itwill/helljava/service/MemberServiceImpl.java
src/main/java/itwill/helljava/service/NoticeServiceServiceImpl.java
src/main/java/itwill/helljava/service/PayServiceImpl.java
src/main/java/itwill/helljava/service/PostingServiceImpl.java

ServiceImpl 클래스 메서드 오버라이드

---

src/main/java/itwill/helljava/dao/PtOnceDAO.java
src/main/java/itwill/helljava/mapper/PtOnceMapper.java
src/main/java/itwill/helljava/service/PtOnceService.java
src/main/java/itwill/helljava/service/PtOnceServiceImpl.java
src/main/java/itwill/helljava/service/PtPricingServiceImpl.java
src/main/java/itwill/helljava/service/PtServiceServiceImpl.java
src/main/java/itwill/helljava/service/ScheduleServiceImpl.java
src/main/java/itwill/helljava/service/TrainerServiceImpl.java

service impl commit

---

src/main/webapp/WEB-INF/views/board/faq_view.jsp
src/main/webapp/WEB-INF/views/board/notice_view.jsp

notice, faq view 세팅시작

---

src/main/java/itwill/helljava/dao/PtOnceDAO.java
src/main/java/itwill/helljava/dao/ScheduleDAO.java
src/main/java/itwill/helljava/mapper/ScheduleMapper.java
src/main/java/itwill/helljava/service/PtOnceService.java
src/main/java/itwill/helljava/service/PtOnceServiceImpl.java
src/main/java/itwill/helljava/service/ScheduleService.java
src/main/java/itwill/helljava/service/ScheduleServiceImpl.java

매개변수 변경 사항 적용

---

src/main/webapp/WEB-INF/views/board/faq_list.jsp
src/main/webapp/WEB-INF/views/board/notice_add.jsp
src/main/webapp/WEB-INF/views/board/notice_list.jsp

Board > 하위 파일명 및 내용 부분 수정

---

src/main/java/itwill/helljava/dao/AccountDAOImpl.java
src/main/java/itwill/helljava/dao/AwardDAOImpl.java
src/main/java/itwill/helljava/dao/MemberDAOImpl.java
src/main/java/itwill/helljava/dao/NoticeServiceDAOImpl.java
src/main/java/itwill/helljava/dao/PayDAOImpl.java
src/main/java/itwill/helljava/dao/PostingDAOImpl.java

DAO Impl 오버라이드 메서드 구현

---

src/main/java/itwill/helljava/dao/PtOnceDAOImpl.java
src/main/java/itwill/helljava/dao/PtPricingDAOImpl.java
src/main/java/itwill/helljava/dao/PtServiceDAOImpl.java
src/main/java/itwill/helljava/dao/ScheduleDAOImpl.java
src/main/java/itwill/helljava/dao/TrainerDAOImpl.java
src/main/java/itwill/helljava/mapper/PtOnceMapper.java

daoImpl commit

---

src/main/java/itwill/helljava/dao/PtOnceDAO.java
src/main/java/itwill/helljava/dao/PtOnceDAOImpl.java
src/main/java/itwill/helljava/dao/PtServiceDAO.java
src/main/java/itwill/helljava/dao/PtServiceDAOImpl.java
src/main/java/itwill/helljava/mapper/PtOnceMapper.java
src/main/java/itwill/helljava/mapper/PtServiceMapper.java
src/main/java/itwill/helljava/service/PtOnceService.java
src/main/java/itwill/helljava/service/PtOnceServiceImpl.java
src/main/java/itwill/helljava/service/PtServiceService.java
src/main/java/itwill/helljava/service/PtServiceServiceImpl.java

트레이너 회원 전용 리스트 => member_status 데이터로 해결

---

src/main/java/itwill/helljava/dao/AccountDAO.java
src/main/java/itwill/helljava/dao/AccountDAOImpl.java
src/main/java/itwill/helljava/mapper/AccountMapper.java
src/main/java/itwill/helljava/mapper/AccountMapper.xml
src/main/java/itwill/helljava/mapper/AwardMapper.xml
src/main/java/itwill/helljava/mapper/MemberMapper.xml
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.xml
src/main/java/itwill/helljava/mapper/PayMapper.xml
src/main/java/itwill/helljava/mapper/PostingMapper.xml
src/main/java/itwill/helljava/service/AccountServiceImpl.java
src/main/java/itwill/helljava/service/AccountSevice.java

mapper.xml 부분 추가

---

src/main/java/itwill/helljava/dao/PtOnceDAO.java
src/main/java/itwill/helljava/dao/PtOnceDAOImpl.java
src/main/java/itwill/helljava/dao/PtServiceDAO.java
src/main/java/itwill/helljava/mapper/PtOnceMapper.java
src/main/java/itwill/helljava/mapper/PtOnceMapper.xml
src/main/java/itwill/helljava/mapper/PtPricingMapper.xml
src/main/java/itwill/helljava/mapper/PtServiceMapper.xml
src/main/java/itwill/helljava/mapper/ScheduleMapper.xml
src/main/java/itwill/helljava/mapper/TrainerMapper.xml
src/main/java/itwill/helljava/service/PtOnceService.java
src/main/java/itwill/helljava/service/PtOnceServiceImpl.java

mapper.xml commit

---

src/main/java/itwill/helljava/controller/NoticeController.java
src/main/webapp/WEB-INF/views/board/notice_modify.jsp
src/main/webapp/WEB-INF/views/board/notice_write.jsp

notice 관련 파일 수정

---

src/main/java/itwill/helljava/mapper/TrainerMapper.xml

trainerMapper.xml 중간 commit

---

src/main/java/itwill/helljava/mapper/PayMapper.java
src/main/java/itwill/helljava/mapper/PayMapper.xml
src/main/java/itwill/helljava/mapper/PostingMapper.xml
src/main/java/itwill/helljava/mapper/PtServiceMapper.xml

pt_service count select 추가
pay mapper 추가
insert 관련 이슈 살피자

pt_service count select 추가  pay mapper 추가  insert 관련 이슈 살피자

---

src/main/webapp/WEB-INF/views/layout/template.jsp

template 부트스트랩 경로 설정

---

src/main/java/itwill/helljava/mapper/AccountMapper.xml
src/main/java/itwill/helljava/mapper/AwardMapper.xml
src/main/java/itwill/helljava/mapper/MemberMapper.xml
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.xml
src/main/java/itwill/helljava/mapper/PayMapper.xml
src/main/java/itwill/helljava/mapper/PostingMapper.xml

null 문제 jdbcType 명시

---

src/main/java/itwill/helljava/mapper/TrainerMapper.xml

trainermapper commit

---

src/main/java/itwill/helljava/controller/NoticeController.java
src/main/webapp/WEB-INF/views/board/notice_list.jsp
src/main/webapp/WEB-INF/views/board/notice_write.jsp

notice commit

---

src/main/java/itwill/helljava/mapper/AwardMapper.java
src/main/java/itwill/helljava/mapper/MemberMapper.java
src/main/java/itwill/helljava/mapper/MemberMapper.xml
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.java
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.xml
src/main/java/itwill/helljava/mapper/PtOnceMapper.java
src/main/java/itwill/helljava/mapper/PtOnceMapper.xml
src/main/java/itwill/helljava/mapper/PtPricingMapper.java
src/main/java/itwill/helljava/mapper/PtServiceMapper.java
src/main/java/itwill/helljava/mapper/PtServiceMapper.xml
src/main/java/itwill/helljava/mapper/ScheduleMapper.java
src/main/java/itwill/helljava/mapper/ScheduleMapper.xml
src/main/java/itwill/helljava/mapper/TrainerMapper.java
src/main/java/itwill/helljava/mapper/TrainerMapper.xml

SQL 변경 사항 적용

---

src/main/java/itwill/helljava/service/AwardService.java
src/main/java/itwill/helljava/service/AwardServiceImpl.java

award까지 수정 commit

---

src/main/java/itwill/helljava/dao/MemberDAO.java
src/main/java/itwill/helljava/dao/MemberDAOImpl.java
src/main/java/itwill/helljava/dao/NoticeServiceDAO.java
src/main/java/itwill/helljava/dao/NoticeServiceDAOImpl.java
src/main/java/itwill/helljava/dao/PtOnceDAO.java
src/main/java/itwill/helljava/dao/PtOnceDAOImpl.java
src/main/java/itwill/helljava/dao/PtPricingDAO.java
src/main/java/itwill/helljava/dao/PtServiceDAO.java
src/main/java/itwill/helljava/dao/PtServiceDAOImpl.java
src/main/java/itwill/helljava/dao/ScheduleDAO.java
src/main/java/itwill/helljava/dao/ScheduleDAOImpl.java
src/main/java/itwill/helljava/dao/TrainerDAO.java
src/main/java/itwill/helljava/dao/TrainerDAOImpl.java
src/main/java/itwill/helljava/service/AwardService.java
src/main/java/itwill/helljava/service/MemberService.java
src/main/java/itwill/helljava/service/MemberServiceImpl.java
src/main/java/itwill/helljava/service/NoticeServiceService.java
src/main/java/itwill/helljava/service/NoticeServiceServiceImpl.java
src/main/java/itwill/helljava/service/PostingService.java
src/main/java/itwill/helljava/service/PtOnceService.java
src/main/java/itwill/helljava/service/PtOnceServiceImpl.java
src/main/java/itwill/helljava/service/PtServiceService.java
src/main/java/itwill/helljava/service/PtServiceServiceImpl.java
src/main/java/itwill/helljava/service/ScheduleService.java
src/main/java/itwill/helljava/service/ScheduleServiceImpl.java
src/main/java/itwill/helljava/service/TrainerService.java
src/main/java/itwill/helljava/service/TrainerServiceImpl.java

메소드 맞춰주기 수정

---

src/main/java/itwill/helljava/service/TrainerService.java
src/main/java/itwill/helljava/service/TrainerServiceImpl.java

trainerservice commit

---

src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml

servlet-context 수정

---

src/main/java/itwill/helljava/mapper/AccountMapper.xml
src/main/java/itwill/helljava/mapper/PtServiceMapper.xml
src/main/java/itwill/helljava/service/PtOnceServiceImpl.java
src/main/java/itwill/helljava/service/PtPricingServiceImpl.java
src/main/java/itwill/helljava/service/PtServiceServiceImpl.java
src/main/java/itwill/helljava/service/ScheduleServiceImpl.java
src/main/java/itwill/helljava/service/TrainerServiceImpl.java

accountmapper 공백수정,@Transactional 추가

accountmapper 공백수정,@Transactional 추가

---

src/test/java/itwill/helljava/service/AccountServiceTest.java

service 패키지 생성

---

pom.xml
src/main/java/itwill/helljava/mapper/AccountMapper.xml
src/main/resources/log4j.xml
src/test/java/itwill/helljava/controller/AccountServiceTest.java

xml 파일들 변경

---

src/main/java/itwill/helljava/controller/NoticeController.java
src/main/webapp/WEB-INF/views/board/notice_list.jsp
src/main/webapp/WEB-INF/views/board/notice_modify.jsp
src/main/webapp/WEB-INF/views/board/notice_write.jsp
src/main/webapp/WEB-INF/views/layout/footer.jsp

notice, 푸터 수정 커밋.

---

src/main/java/itwill/helljava/controller/DetailSearchController.java
src/main/webapp/WEB-INF/views/content/posting_detail.jsp
src/main/webapp/WEB-INF/views/content/posting_detail_insert.jsp
src/main/webapp/WEB-INF/views/content/search_list.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/WEB-INF/views/layout/main.jsp
src/main/webapp/WEB-INF/views/user/login/id_search.jsp
src/main/webapp/WEB-INF/views/user/login/login_form.jsp
src/main/webapp/WEB-INF/views/user/login/password_search.jsp
src/main/webapp/WEB-INF/views/user/login/password_update.jsp
src/main/webapp/resources/assets/css/main.css

posting insert add

---

src/main/webapp/WEB-INF/views/layout/footer.jsp
src/main/webapp/WEB-INF/views/layout/main.jsp
src/main/webapp/resources/assets/css/new-main.css

footer update

---

src/main/java/itwill/helljava/Enum/NoticeServiceCategoryEnum.java
src/main/java/itwill/helljava/Enum/NoticeServiceSortationEnum.java
src/main/java/itwill/helljava/Enum/NoticeServiceStatusEnum.java
src/main/java/itwill/helljava/Enum/PtServiceSortationEnum.java
src/main/java/itwill/helljava/Enum/PtServiceStatusEnum.java

Enum Commit

---

src/main/webapp/WEB-INF/views/board/notice_list.jsp

notice list el 수정.

---

src/main/java/itwill/helljava/mapper/NoticeServiceMapper.xml

NoticeServiceMapper Commit

---

src/main/java/itwill/helljava/Enum/MemberEnum.java
src/main/java/itwill/helljava/dao/TrainerDAO.java
src/main/java/itwill/helljava/dao/TrainerDAOImpl.java
src/main/java/itwill/helljava/mapper/TrainerMapper.java
src/main/java/itwill/helljava/mapper/TrainerMapper.xml
src/main/java/itwill/helljava/service/TrainerService.java
src/main/java/itwill/helljava/service/TrainerServiceImpl.java
src/test/java/itwill/helljava/controller/TrainerServiceTest.java

enum 상수 이름 변경 및sql 추가

---

src/main/java/itwill/helljava/Enum/NoticeServiceStatusEnum.java

NoticeServiceStatusEnum 수정

---

src/main/java/itwill/helljava/exception/MemberExistsException.java
src/main/java/itwill/helljava/mapper/TrainerMapper.xml

memberExistsException 추가, TrainerMapper 수정

memberExistsException 추가, TrainerMapper 수정

---

src/main/java/itwill/helljava/exception/MemberNotFoundException.java

MemberNotFoundException 추가

---

src/main/java/itwill/helljava/exception/LoginAuthFailException.java

loginAuthFailException 추가

---

src/main/java/itwill/helljava/controller/joinController.java

joincontroller exceptionHandler

joincontroller exceptionHandler

---

src/main/java/itwill/helljava/exception/MemberIdSearchNotFoundException.java
src/main/java/itwill/helljava/exception/MemberPwSearchNotFoundException.java

아이디찾기, 비밀번호찾기 Exception 추가

---

src/main/webapp/WEB-INF/views/user/login/password_search.jsp
src/main/webapp/WEB-INF/views/user/login/password_update.jsp

password commit

---

src/main/java/itwill/helljava/mapper/NoticeServiceMapper.xml

noticeServiceMapper 수정

---

src/main/webapp/WEB-INF/views/layout/header.jsp

header mypage 경로 설정

---

src/main/java/itwill/helljava/controller/TilesController.java

mypage tilescontroller에 임시 설정

---

src/main/java/itwill/helljava/mapper/AwardMapper.xml
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.xml
src/main/java/itwill/helljava/mapper/PayMapper.xml
src/main/java/itwill/helljava/mapper/PostingMapper.xml
src/main/java/itwill/helljava/mapper/PtOnceMapper.xml
src/main/java/itwill/helljava/mapper/PtPricingMapper.xml
src/main/java/itwill/helljava/mapper/PtServiceMapper.xml
src/main/java/itwill/helljava/mapper/ScheduleMapper.xml
src/main/java/itwill/helljava/mapper/TrainerMapper.xml
src/main/webapp/WEB-INF/views/board/faq_write.jsp

mapper.xml 수정

---

src/main/java/itwill/helljava/controller/AccountController.java
src/main/java/itwill/helljava/mapper/AccountMapper.xml
src/main/webapp/WEB-INF/views/account/account_info.jsp
src/main/webapp/WEB-INF/views/account/account_register.jsp
src/main/webapp/WEB-INF/views/material/mypage.jsp

account commit

---

src/main/webapp/WEB-INF/views/layout/footer.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/WEB-INF/views/layout/main.jsp
src/main/webapp/WEB-INF/views/user/join_form.jsp

헤더 풋터 메인 jsp 수정

---

src/main/java/itwill/helljava/controller/AccountController.java
src/main/java/itwill/helljava/service/AccountServiceImpl.java
src/main/webapp/WEB-INF/views/account/account_info.jsp

계좌 jsp, controller 수정

---

src/main/java/itwill/helljava/controller/AccountController.java
src/main/java/itwill/helljava/controller/ExceptionController.java
src/main/java/itwill/helljava/controller/UserinfoController.java
src/main/java/itwill/helljava/util/AdminAuthInterceptor.java
src/main/java/itwill/helljava/util/LoginAuthInterceptor.java
src/main/webapp/WEB-INF/spring/appServlet/servlet-context.xml

예외 처리 컨트롤러 및 클래스 생성

---

src/main/java/itwill/helljava/controller/NoticeController.java

불필요 메소드 제거

---

src/main/webapp/WEB-INF/views/board/faq_view.jsp
src/main/webapp/WEB-INF/views/board/notice_list.jsp
src/main/webapp/WEB-INF/views/layout/footer.jsp

list, footer

---

src/main/webapp/WEB-INF/views/account/account_info.jsp
src/main/webapp/WEB-INF/views/account/account_register.jsp
src/main/webapp/WEB-INF/views/board/notice_view.jsp
src/main/webapp/WEB-INF/views/content/search_list.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/resources/assets/css/main.css
src/main/webapp/resources/assets/css/my-css.css

css commit

---

src/main/java/itwill/helljava/controller/HomeController.java
src/main/java/itwill/helljava/controller/OneOnOneController.java

tilesController > homeController 이름 변경

일부 컨트롤러 수정

---

src/main/java/itwill/helljava/controller/OneOnOneController.java

oOo컨트롤러 수정 커밋

---

src/main/webapp/WEB-INF/views/content/posting_detail.jsp

posting_detail

---

src/main/webapp/WEB-INF/views/account/account_info.jsp
src/main/webapp/WEB-INF/views/user/member_modify.jsp
src/main/webapp/resources/assets/css/my-css.css

account info, member_modify, css 수정

account info, member_modify, css 수정

---

src/main/webapp/WEB-INF/views/user/member_modify.jsp

연락처 양식 변경, 유효성 검사 삽입, 텍스트 폰트 크기 및 패딩 정렬

회원 정보 변경 화면 수정

---

src/main/java/itwill/helljava/controller/PostingController.java
src/main/webapp/WEB-INF/views/content/posting_detail_insert.jsp

포스팅 디테일 추가 수정

---

src/main/webapp/WEB-INF/views/admin/admin_questionList.jsp
src/main/webapp/WEB-INF/views/admin/admin_trainerList.jsp
src/main/webapp/WEB-INF/views/admin/admin_userList.jsp
src/main/webapp/WEB-INF/views/user/join_form.jsp
src/main/webapp/resources/assets/css/my-css.css

관리자페이지, css 수정

---

src/main/webapp/WEB-INF/views/admin/admin_userList.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/WEB-INF/views/user/trainer/trainer_request.jsp

트레이너 신청페이지, 헤더 수정

---

src/main/java/itwill/helljava/controller/OneOnOneController.java
src/main/webapp/WEB-INF/views/board/oOo_list.jsp
src/main/webapp/WEB-INF/views/board/oOo_write.jsp

oOo controller, list 수정

---

src/main/webapp/WEB-INF/views/board/oOo_list.jsp
src/main/webapp/WEB-INF/views/board/ptonce_list.jsp

리스트 페이지 커밋.

---

src/main/webapp/WEB-INF/views/material/mypage.jsp
src/main/webapp/WEB-INF/views/user/member_modify.jsp
src/main/webapp/resources/assets/css/my-css.css

내정보수정,마이페이지, css 수정

---

src/main/webapp/WEB-INF/views/user/trainer/trainer_request.jsp

트레이너신청 css

---

src/main/webapp/WEB-INF/views/board/faq_view.jsp
src/main/webapp/WEB-INF/views/board/notice_view.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/WEB-INF/views/user/oOo/oOo_list.jsp
src/main/webapp/resources/assets/css/my-css.css

게시판 view, 1대1문의 list, css 수정

---

src/main/webapp/WEB-INF/views/user/trainer/trainer_mypage.jsp

트레이너 마이페이지 수정

---

src/main/java/itwill/helljava/controller/PtQnAController.java
src/main/java/itwill/helljava/mapper/PtServiceMapper.xml
src/main/webapp/WEB-INF/views/material/terms1.jsp
src/main/webapp/WEB-INF/views/material/terms2.jsp
src/main/webapp/WEB-INF/views/user/ptQnA/ptQnA_list_confirm.jsp
src/main/webapp/WEB-INF/views/user/ptQnA/ptQnA_list_miss.jsp

pt 문의 관련 커밋, 맵퍼 수정

---

src/main/webapp/WEB-INF/views/content/posting_detail.jsp
src/main/webapp/WEB-INF/views/user/trainer/trainer_request.jsp
src/main/webapp/resources/assets/css/my-css.css

포스팅디테일모달창, css 수정

---

src/main/webapp/resources/assets/css/new-main.css

new-main.css 모달css 수정

---

src/main/webapp/resources/assets/css/new-main.css

new-main.css

---

src/main/java/itwill/helljava/mapper/PtOnceMapper.xml

ptOnceMapper 일부 수정

---

src/main/java/itwill/helljava/mapper/PtOnceMapper.xml

ptonce mapper xml 수정

---

src/main/webapp/WEB-INF/views/content/posting_detail.jsp
src/main/webapp/WEB-INF/views/user/join_form.jsp
src/main/webapp/resources/assets/css/my-css.css

회원가입, 포스팅디테일 수정

---

src/main/webapp/WEB-INF/views/board/faq_write.jsp
src/main/webapp/WEB-INF/views/board/notice_write.jsp
src/main/webapp/WEB-INF/views/user/ptQnA/ptQnA_list.jsp
src/main/webapp/WEB-INF/views/user/ptonce/ptonce_list.jsp
src/main/webapp/resources/assets/css/my-css.css

faq작성, 1회피티리스트, 피티문의리스트,공지사항작성 수정

faq작성, 1회피티리스트, 피티문의리스트,공지사항작성 수정

---

src/main/webapp/WEB-INF/views/user/oOo/oOo_list.jsp
src/main/webapp/WEB-INF/views/user/ptQnA/ptQnA_list.jsp
src/main/webapp/WEB-INF/views/user/ptonce/ptonce_list.jsp
src/main/webapp/resources/assets/css/my-css.css

마이페이지 게시판 css 추가

---

src/main/webapp/WEB-INF/views/user/ptQnA/ptQnA_list.jsp
src/main/webapp/WEB-INF/views/user/ptonce/ptonce_list.jsp
src/main/webapp/resources/assets/css/my-css.css

피티문의, 1회피티

---

src/main/webapp/WEB-INF/views/user/oOo/oOo_list.jsp
src/main/webapp/WEB-INF/views/user/oOo/oOo_write.jsp

1대1 리스트, 작성페이지 수정

---

src/main/webapp/WEB-INF/views/user/ptQnA/ptQnA_list.jsp

ptqnalist 수정

---

src/main/webapp/WEB-INF/views/content/posting_detail_insert.jsp
src/main/webapp/WEB-INF/views/user/trainer/trainer_request.jsp
src/main/webapp/resources/assets/css/my-css.css

[포스팅작성, 트레이너신청 수정](https://github.com/redmango1446/hell-s-java/commit/095fdd1d99f793fc2e8d980c4f3ec054e04c3de3)

포스팅작성, 트레이너신청 수정

---

src/main/webapp/WEB-INF/views/content/posting_detail_insert.jsp
src/main/webapp/WEB-INF/views/user/trainer/trainer_request.jsp
src/main/webapp/resources/assets/css/my-css.css

포스팅디테일작성, 트레이너신청 수정

---

src/main/java/itwill/helljava/controller/ReviewController.java
src/main/java/itwill/helljava/mapper/PtOnceMapper.xml
src/main/webapp/WEB-INF/views/board/review_write.jsp
src/main/webapp/WEB-INF/views/user/ptonce/ptonce_list.jsp

ptonce review 쿼리문 수정 및 컨트롤러 수정!

ptonce review 쿼리문 수정 및 컨트롤러 수정!

---

src/main/webapp/WEB-INF/views/content/posting_detail.jsp
src/main/webapp/WEB-INF/views/user/trainer/trainer_request.jsp
src/main/webapp/resources/assets/css/my-css.css

포스팅디테일, 트레이너신청 수정

---

src/main/webapp/WEB-INF/views/admin/admin_trainerList.jsp
src/main/webapp/WEB-INF/views/admin/testaward.jsp
src/main/webapp/resources/assets/css/my-css.css

관리자트레이너리스트, 수상내역

---

src/main/webapp/WEB-INF/views/user/mypage.jsp
src/main/webapp/WEB-INF/views/user/trainer/trainer_request.jsp

트레이너신청, 마이페이지 수정

---

src/main/webapp/WEB-INF/views/layout/footer.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/WEB-INF/views/user/ptonce/ptonce_list.jsp

1회피티 제목 글자수정

---

src/main/java/itwill/helljava/controller/FAQController.java
src/main/webapp/WEB-INF/views/board/faq_list.jsp
src/main/webapp/WEB-INF/views/board/faq_list3.jsp

검색 기능 전까지 수정
* 검색 기능 추가, 데이터 널 유효성 검사 추가해야 함

FAQ  일부 수정

---

src/main/webapp/WEB-INF/views/layout/footer.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/resources/assets/css/my-css.css

header,footer,my-css 수정

---

src/main/webapp/WEB-INF/views/layout/header.jsp
src/main/webapp/resources/assets/css/my-css.css

헤더, css 수정

---

src/main/java/itwill/helljava/controller/TrainerController.java
src/main/java/itwill/helljava/mapper/AwardMapper.xml

트레이너컨트롤러, 어워드 수정

---

src/main/java/itwill/helljava/controller/PtOnceController.java
src/main/java/itwill/helljava/controller/TrainerController.java
src/main/java/itwill/helljava/exception/AmountOfPaymentException.java
src/main/java/itwill/helljava/exception/NoticeServiceNotFoundException.java
src/main/java/itwill/helljava/service/PayService.java
src/main/java/itwill/helljava/service/PayServiceImpl.java
src/main/webapp/WEB-INF/views/content/posting_detail.jsp
src/main/webapp/WEB-INF/views/user/trainer/trainer_request.jsp

2. 라인 정리
3. payAuto 메서드 정의
4. PtOnceController & TrainerController 예외 처리 핸들러 메서드 추가
5. jsp에서 메시지 추가

1. 잔액 예외 클래스 추가2. 라인 정리  3. payAuto 메서드 정의  4. PtOnceController & TrainerController 예외 처리 핸들러 메서드 추가  5. jsp에서 메시지 추가

---

src/main/java/itwill/helljava/dao/PostingDAO.java
src/main/java/itwill/helljava/dao/PostingDAOImpl.java
src/main/java/itwill/helljava/dao/TrainerDAO.java
src/main/java/itwill/helljava/dao/TrainerDAOImpl.java
src/main/java/itwill/helljava/dto/Trainer.java
src/main/java/itwill/helljava/mapper/TrainerMapper.java
src/main/java/itwill/helljava/mapper/TrainerMapper.xml
src/main/java/itwill/helljava/service/PostingService.java
src/main/java/itwill/helljava/service/PostingServiceImpl.java
src/main/java/itwill/helljava/service/TrainerService.java
src/main/java/itwill/helljava/service/TrainerServiceImpl.java
src/test/java/itwill/helljava/controller/TrainerServiceTest.java

메인에서 리뷰 많은 순 트레이너 3개 뽑기 관련 추가

---

src/main/java/itwill/helljava/controller/FAQController.java
src/main/java/itwill/helljava/dao/NoticeServiceDAO.java
src/main/java/itwill/helljava/dao/NoticeServiceDAOImpl.java
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.java
src/main/java/itwill/helljava/mapper/NoticeServiceMapper.xml
src/main/java/itwill/helljava/service/NoticeServiceService.java
src/main/java/itwill/helljava/service/NoticeServiceServiceImpl.java
src/main/webapp/WEB-INF/views/board/faq_list.jsp

FAQ 검색 및 페이징 및 카테고리 관련 처리

---

src/main/webapp/WEB-INF/views/layout/main.jsp

main.jsp trainer 오타 수정

---

src/main/java/itwill/helljava/controller/UserinfoController.java

1. 회원 정보 수정 경로 수정
2. 수정 정보 session 닮음

UserinfoController 수정

---

src/main/java/itwill/helljava/dao/MemberDAO.java
src/main/java/itwill/helljava/dao/MemberDAOImpl.java
src/main/java/itwill/helljava/dao/PayDAO.java
src/main/java/itwill/helljava/dao/PayDAOImpl.java
src/main/java/itwill/helljava/dto/Member.java
src/main/java/itwill/helljava/mapper/MemberMapper.java
src/main/java/itwill/helljava/mapper/MemberMapper.xml
src/main/java/itwill/helljava/mapper/PayMapper.java
src/main/java/itwill/helljava/mapper/PayMapper.xml
src/main/java/itwill/helljava/service/MemberService.java
src/main/java/itwill/helljava/service/MemberServiceImpl.java
src/main/java/itwill/helljava/service/PayService.java
src/main/java/itwill/helljava/service/PayServiceImpl.java
src/main/java/itwill/helljava/util/TrainerScheduler.java
src/main/resources/log4j.xml
src/main/webapp/WEB-INF/spring/root-context.xml

자동 결제 관련 추가 sql, logger, scheduler, xml 추가

자동 결제 관련 추가 sql, logger, scheduler, xml 추가

---

src/main/java/itwill/helljava/controller/PostingController.java
src/main/java/itwill/helljava/dao/PayDAO.java
src/main/java/itwill/helljava/dao/PayDAOImpl.java
src/main/java/itwill/helljava/mapper/PayMapper.java
src/main/java/itwill/helljava/mapper/PayMapper.xml
src/main/java/itwill/helljava/service/PayService.java
src/main/java/itwill/helljava/service/PayServiceImpl.java
src/main/java/itwill/helljava/util/TrainerScheduler.java
src/main/webapp/WEB-INF/views/content/posting_detail.jsp

자동 결제 관련 sql controller jsp 수정 및 캐시 잔액 예외 처리

자동 결제 관련 sql controller jsp 수정 및 캐시 잔액 예외 처리

---

src/main/java/itwill/helljava/mapper/PtServiceMapper.xml
src/main/java/itwill/helljava/mapper/TrainerMapper.xml
src/main/webapp/WEB-INF/views/content/posting_detail.jsp

sql 포스팅 범위 관련 수정

---

src/main/java/itwill/helljava/controller/HomeController.java

메인 페이지 메서드 잠시 주석

---

src/main/java/itwill/helljava/controller/HomeController.java
src/main/java/itwill/helljava/controller/TrainerController.java

주석 해제 및 status 값 추가 트레이너 신청 시

---

src/main/webapp/WEB-INF/views/admin/admin_trainerList.jsp
src/main/webapp/WEB-INF/views/layout/header.jsp

헤더 칭호 변경 및 관리자 트레이너 리스트에서 회원 변경 추가

헤더 칭호 변경 및 관리자 트레이너 리스트에서 회원 변경 추가

---

src/main/java/itwill/helljava/service/MemberServiceImpl.java

탈퇴회원 로그인 인증 처리 추가

---

src/main/webapp/WEB-INF/views/account/account_register.jsp
src/main/webapp/WEB-INF/views/content/posting_detail.jsp

맵 api 서버 도메인 변경 및 계좌 등록 시 은행 명 선택 수정

맵 api 서버 도메인 변경 및 계좌 등록 시 은행 명 선택 수정

---

src/main/java/itwill/helljava/controller/PtOnceController.java
src/main/webapp/WEB-INF/views/content/posting_detail.jsp

넘버 포맷 substring

---

src/main/java/itwill/helljava/controller/TrainerController.java

Trainer 정보 수정 시 프로필 이미지 변경에서 기존 파일 delete() 추가

Trainer 정보 수정 시 프로필 이미지 변경에서 기존 파일 delete() 추가
